### ISSUE TITLE
IMPORTANT - Merge #3 needs to be backed out

### ISSUE THREAD

**Issue by Kys3rK1ng** [xhteam/tools-motodev#4]
A pull request created by Kys3rk1ng for Andmore has just been merged into xteam/tools-motodev. This pull request was created in error and should have been cancelled. I am not an expert on Git, but I expect that an unmerge procedure should not be difficult as long as no other changes are made on top of the merge. You should also be aware that one more commit was made to the pull request branch to fix a build issue.

I apologise for any inconvience caused by the original error.

**Comment by raymond1860** [comment]
It's reverted now.
